### ISSUE TITLE
example "mnist_simple.jl" fails as well

### ISSUE THREAD

**Issue by montyvesselinov** [malmaud/TensorFlow.jl#462] opened 2018-10-30 19:17 UTC
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin14.5.0

julia> using TensorFlow

shell> cd .julia/packages/TensorFlow/A6TdG/examples/
/Users/monty/.julia/packages/TensorFlow/A6TdG/examples

julia> include("mnist_simple.jl")
2018-10-30 13:12:09.672349: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
ERROR: LoadError: Tensorflow error: Status: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: gradients/reduce_2_grad/Cast = Cast[DstT=DT_FLOAT, SrcT=DT_INT32, Truncate=false](gradients/reduce_2_grad/floordiv_1). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

Stacktrace:
 [1] check_status at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/core.jl:374 [inlined]
 [2] import_graph_def(::Graph, ::Array{UInt8,1}, ::GraphImportOptions) at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/core.jl:1653
 [3] import_graph_def at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/core.jl:1664 [inlined]
 [4] extend_graph(::Graph, ::Array{Any,1}) at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/core.jl:341
 [5] extend_graph(::Array{Any,1}) at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/core.jl:217
 [6] macro expansion at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/TensorFlow.jl:181 [inlined]
 [7] add_gradients_py(::Tensor{Float32}, ::Array{Any,1}, ::Nothing) at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/core.jl:1545
 [8] gradients at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/core.jl:1533 [inlined] (repeats 2 times)
 [9] compute_gradients(::TensorFlow.train.GradientDescentOptimizer, ::Tensor{Float32}, ::Nothing) at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/train.jl:49
 [10] #minimize#1(::Nothing, ::Nothing, ::Nothing, ::Function, ::TensorFlow.train.GradientDescentOptimizer, ::Tensor{Float32}) at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/train.jl:41
 [11] minimize(::TensorFlow.train.GradientDescentOptimizer, ::Tensor{Float32}) at /Users/monty/.julia/packages/TensorFlow/A6TdG/src/train.jl:38
 [12] top-level scope at none:0
 [13] include at ./boot.jl:317 [inlined]
 [14] include_relative(::Module, ::String) at ./loading.jl:1038
 [15] include(::Module, ::String) at ./sysimg.jl:29
 [16] include(::String) at ./client.jl:398
 [17] top-level scope at none:0
in expression starting at /Users/monty/.julia/packages/TensorFlow/A6TdG/examples/mnist_simple.jl:19
```

**Comment by oxinabox** [comment] 2018-10-31 10:07
Duplicate of #461 .
See solution/discussion there.

**Closed by oxinabox** 2018-10-31 10:07 UTC
