### ISSUE TITLE
TensorFlow version number disagrees with download name

### ISSUE THREAD

**Issue by jgbos** [malmaud/TensorFlow.jl#229] opened 2017-05-26 23:56 UTC
From `master`, when I do `Pkg.build` on my Mac, it downloads the mac version from 

`https://storage.googleapis.com/malmaud-stuff/tensorflow_mac_1.1.0.zip`

But when I do `TensorFlow.tf_version()` I get `v1.0.1`.

**Comment by oxinabox** [comment] 2017-05-27 02:06
What version of TensorFlow.jl?

**Comment by jgbos** [comment] 2017-05-27 02:26
I'm using the most recent `master` branch.  I'm running into an issue because my python version is `v1.1.0` but the version from the download appears to be `v1.0.1`.

**Comment by oxinabox** [comment] 2017-05-27 12:51
I have reproduced this on master, on linux.

**Comment by malmaud** [comment] 2017-05-27 13:32
If memory serves, the current binaries were actually build against upstream head because the released version didn't have all the APIs we needed. We should just rebuild the binaries now that 1.1.0 is out.

**Comment by aterenin** [comment] 2017-05-30 02:03
I can confirm this on OS X. See also #220. If you drop in a 1.0.1 binary compiled elsewhere, you will get errors when calling `tf.gradients` and probably other stuff I haven't tested.

**Comment by malmaud** [comment] 2017-05-31 18:36
Since 1.2.0 is almost out, I'll just wait for that and then rebuild all the binaries.

**Comment by malmaud** [comment] 2017-07-07 22:47
Closed in https://github.com/malmaud/TensorFlow.jl/pull/267

**Closed by malmaud** 2017-07-07 22:47 UTC
Labels: installation/libtensorflow
